import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fauzan Idal Fithri E
 */
public class ClientPage extends javax.swing.JFrame {

    /**
     * Creates new form clientPage
     */
    public ClientPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        reload();
    }
    
    public void reload(){
        try {
            Object[] colPesawat = {"No","Maskapai","Asal","Tujuan","Tanggal Keberangkatan"};
            Object[][] dataPesawat;
            Registry registry = LocateRegistry.getRegistry("192.168.137.2",Registry.REGISTRY_PORT);
            IPesawat stubPesawat = (IPesawat) registry.lookup("Pesawat");
            List<Pesawat> listPesawat = (List)stubPesawat.getPesawats();
            dataPesawat = new Object[listPesawat.size()][colPesawat.length];
            int i = 0;
            for (Pesawat s:listPesawat) {
                dataPesawat[i][0] = 1+i;
                dataPesawat[i][1] = s.getMaskapai();
                dataPesawat[i][2] = s.getAsal();
                dataPesawat[i][3] = s.getTujuan();
                dataPesawat[i][4] = s.getTanggal();
                i++;
            }
            DefaultTableModel modelTabelTiketPesawat = (DefaultTableModel) tableTiketPesawat.getModel();
            modelTabelTiketPesawat.setDataVector(dataPesawat, colPesawat);
        } catch (Exception e) { 
            System.err.println("Client exception: " + e.toString());
            e.printStackTrace();
        }
        try {
            Object[] colBioskop = {"No","Film","Bioskop","Studio"};
            Object[][] dataBioskop = {};
            Registry registry = LocateRegistry.getRegistry("192.168.137.3",Registry.REGISTRY_PORT);
            IBioskop stubBioskop = (IBioskop) registry.lookup("Bioskop");
            List<Bioskop> listBioskop = (List)stubBioskop.getBioskops();
            dataBioskop = new Object[listBioskop.size()][colBioskop.length];
            int i = 0;
            for (Bioskop b:listBioskop){ 
                dataBioskop[i][0] = 1+i;
                dataBioskop[i][1] = b.getNama_film();
                dataBioskop[i][2] = b.getNama_bioskop();
                dataBioskop[i][3] = b.getNo_studio();
                i++;
            }
            DefaultTableModel modelTabelTiketBioskop = (DefaultTableModel) tableTiketBioskop.getModel();
            modelTabelTiketBioskop.setDataVector(dataBioskop, colBioskop);
        } catch (Exception e) { 
            System.err.println("Client exception: " + e.toString());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabTiket = new javax.swing.JTabbedPane();
        tabTiketPesawat = new javax.swing.JScrollPane();
        tableTiketPesawat = new javax.swing.JTable();
        tabTiketBioskop = new javax.swing.JScrollPane();
        tableTiketBioskop = new javax.swing.JTable();
        reloadButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tiket");
        setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        setForeground(java.awt.Color.black);
        setResizable(false);

        tableTiketPesawat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Maskapai", "Asal", "Tujuan", "Tanggal Keberangkatan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabTiketPesawat.setViewportView(tableTiketPesawat);

        tabTiket.addTab("Tiket Pesawat", tabTiketPesawat);

        tableTiketBioskop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Film", "Bioskop", "Studio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTiketBioskop.getTableHeader().setReorderingAllowed(false);
        tabTiketBioskop.setViewportView(tableTiketBioskop);
        if (tableTiketBioskop.getColumnModel().getColumnCount() > 0) {
            tableTiketBioskop.getColumnModel().getColumn(0).setPreferredWidth(1);
            tableTiketBioskop.getColumnModel().getColumn(3).setPreferredWidth(1);
        }

        tabTiket.addTab("Tiket Bioskop", tabTiketBioskop);

        reloadButton.setText("Reload");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabTiket, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(reloadButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(reloadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(tabTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        reload();
    }//GEN-LAST:event_reloadButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton reloadButton;
    private javax.swing.JTabbedPane tabTiket;
    private javax.swing.JScrollPane tabTiketBioskop;
    private javax.swing.JScrollPane tabTiketPesawat;
    private javax.swing.JTable tableTiketBioskop;
    private javax.swing.JTable tableTiketPesawat;
    // End of variables declaration//GEN-END:variables
}
